### ISSUE TITLE
CI/CD setup needed?

### ISSUE THREAD

**Issue by Devidian** [samchon/typia#693]
Hi there,

we started replacing class-validator/class-transformer in our current nest project with nestia/typia. Everything works fine so far locally.
When i push my changes and the CI/CD pipeline runs tests, they fail with messages like:
![image](https://github.com/samchon/typia/assets/10413872/dad6c0b7-da25-46fe-b7e4-b019f87d58c3)
or
![image](https://github.com/samchon/typia/assets/10413872/19f3f567-5b51-41c8-a2e9-6826aa8f0f1e)

do i need to run `npx typia setup` in my pipeline? And if yes, how (because its interactive)?

Best regards

Additional Information:

- Pipeline running on Gitlab
- using node:18
- using yarn 4 (node_modules linker)

**Comment by samchon** [comment]
Can you show me your package.json, tsconfig.json and yaml files of your project?

If you have reproducable repo, it would much better.

Also check that you are using standard TypeScript compiler (not SWC/babel).

**Comment by Devidian** [comment]
The project is a private company project, i need some time to redact parts of the files that might have sensitive data. 
lint is working build is working, only test fails on some apps but not on all. its a nest monorepo.

What i can post now is .gitlab-ci.yml:

```yml
stages:
  - lint
  - test
  - build
  - deploy-image
  - staging
  - production
  - post-production

# Default environment for linting and testing
.node_env:
  image: node:18
  cache:
    key: node
    paths:
      - node_modules/
      - .yarn/

# linter
lint:
  extends: .node_env
  stage: lint
  needs: []
  variables:
    ESLINT_CODE_QUALITY_REPORT: gl-codequality.json
  script:
    - echo $CI_KUBERNETES_ACTIVE
    - yarn
    - yarn lint --format gitlab --quiet
  artifacts:
    reports:
      codequality: gl-codequality.json
  rules:
    - when: on_success

# tester
.test_base:
  extends: .node_env
  stage: test
  needs: [lint]
  before_script:
    - yarn
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

test-redacted-app-name:
  extends: .test_base
  script:
    - yarn test:cov redacted-app-name --collectCoverageFrom="apps/redacted-app-name/src/**/*.(t|j)s"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - changes:
      - apps/redacted-app-name/**/*.spec.ts
```

I'll try to create a public reproduction repo in my personal gitlab, but i've never used gitlab for my own stuff, need to check if i have the same permissions.
